version: '3'

services:
  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/home/node/app
    networks:
      fullcycle:
  db:
    build: ./db
    environment:
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_REPLICA_HOST: db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      fullcycle:

volumes:
  mongodb_data:
    driver: local

networks:
  fullcycle: